spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.248.11:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: foo:com.example.common.Foo1,bar:com.example.common.Bar1
    consumer:
      bootstrap-servers: 192.168.248.11:9092
      properties:
        isolation.level: read_committed
